version: '2'
services:
  db:
    image: postgres:9.5
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
volumes:
  db_data: {}
  redis_data: {}
