version: '3.7'
services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:5.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    environment:
      RABBITMQ_DEFAULT_VHOST: "default"
  web: &web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static:/static
    depends_on:
      - db
      - redis
      - rabbitmq
  worker:
    <<: *web
    command: celery -A {{ cookiecutter.repo_name }} worker -l info 
volumes:
  db_data:
  redis_data:
  static:
